############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "contact"
url = "/contact"
weight = 4





# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "blog"
url = "/blog"
weight = 2

[[footer]]
name = "contact"
url = "/contact"
weight = 3
